# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_forge_global_optspecs
	string join \n p/prompt= conversation= conversation-id= C/directory= sandbox= verbose agent= e/event= h/help V/version
end

function __fish_forge_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_forge_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_forge_using_subcommand
	set -l cmd (__fish_forge_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c forge -n "__fish_forge_needs_command" -s p -l prompt -d 'Direct prompt to process without entering interactive mode' -r
complete -c forge -n "__fish_forge_needs_command" -l conversation -d 'Path to a JSON file containing the conversation to execute' -r -F
complete -c forge -n "__fish_forge_needs_command" -l conversation-id -d 'Conversation ID to use for this session' -r
complete -c forge -n "__fish_forge_needs_command" -s C -l directory -d 'Working directory to use before starting the session' -r -F
complete -c forge -n "__fish_forge_needs_command" -l sandbox -d 'Name for an isolated git worktree to create for experimentation' -r
complete -c forge -n "__fish_forge_needs_command" -l agent -d 'Agent ID to use for this session' -r
complete -c forge -n "__fish_forge_needs_command" -s e -l event -d 'Event to dispatch to the workflow in JSON format' -r
complete -c forge -n "__fish_forge_needs_command" -l verbose -d 'Enable verbose logging output'
complete -c forge -n "__fish_forge_needs_command" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c forge -n "__fish_forge_needs_command" -s V -l version -d 'Print version'
complete -c forge -n "__fish_forge_needs_command" -f -a "agent" -d 'Manage agents'
complete -c forge -n "__fish_forge_needs_command" -f -a "zsh" -d 'Generate shell extension scripts'
complete -c forge -n "__fish_forge_needs_command" -f -a "fish" -d 'Generate fish shell extension scripts'
complete -c forge -n "__fish_forge_needs_command" -f -a "list" -d 'List agents, models, providers, tools, or MCP servers'
complete -c forge -n "__fish_forge_needs_command" -f -a "banner" -d 'Display the banner with version information'
complete -c forge -n "__fish_forge_needs_command" -f -a "info" -d 'Show configuration, active model, and environment status'
complete -c forge -n "__fish_forge_needs_command" -f -a "env" -d 'Display environment information'
complete -c forge -n "__fish_forge_needs_command" -f -a "config" -d 'Get, set, or list configuration values'
complete -c forge -n "__fish_forge_needs_command" -f -a "conversation" -d 'Manage conversation history and state'
complete -c forge -n "__fish_forge_needs_command" -f -a "commit" -d 'Generate and optionally commit changes with AI-generated message'
complete -c forge -n "__fish_forge_needs_command" -f -a "mcp" -d 'Manage Model Context Protocol servers'
complete -c forge -n "__fish_forge_needs_command" -f -a "suggest" -d 'Suggest shell commands from natural language'
complete -c forge -n "__fish_forge_needs_command" -f -a "provider" -d 'Manage API provider authentication'
complete -c forge -n "__fish_forge_needs_command" -f -a "cmd" -d 'Run or list custom commands'
complete -c forge -n "__fish_forge_needs_command" -f -a "workspace" -d 'Manage workspaces for semantic search'
complete -c forge -n "__fish_forge_needs_command" -f -a "data" -d 'Process JSONL data through LLM with schema-constrained tools'
complete -c forge -n "__fish_forge_needs_command" -f -a "vscode" -d 'VS Code integration commands'
complete -c forge -n "__fish_forge_needs_command" -f -a "update" -d 'Update forge to the latest version'
complete -c forge -n "__fish_forge_needs_command" -f -a "setup" -d 'Setup zsh integration by updating .zshrc with plugin and theme (alias for `zsh setup`)'
complete -c forge -n "__fish_forge_needs_command" -f -a "doctor" -d 'Run diagnostics on shell environment (alias for `zsh doctor`)'
complete -c forge -n "__fish_forge_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand agent; and not __fish_seen_subcommand_from list help" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand agent; and not __fish_seen_subcommand_from list help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand agent; and not __fish_seen_subcommand_from list help" -f -a "list" -d 'List available agents'
complete -c forge -n "__fish_forge_using_subcommand agent; and not __fish_seen_subcommand_from list help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand agent; and __fish_seen_subcommand_from list" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand agent; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand agent; and __fish_seen_subcommand_from help" -f -a "list" -d 'List available agents'
complete -c forge -n "__fish_forge_using_subcommand agent; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "plugin" -d 'Generate shell plugin script'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "theme" -d 'Generate shell theme'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "doctor" -d 'Run diagnostics on shell environment'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "rprompt" -d 'Get rprompt information (model and conversation stats) for shell integration'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "setup" -d 'Setup zsh integration by updating .zshrc with plugin and theme'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "keyboard" -d 'Show keyboard shortcuts for ZSH line editor'
complete -c forge -n "__fish_forge_using_subcommand zsh; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from plugin" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from theme" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from doctor" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from rprompt" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from setup" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from keyboard" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from help" -f -a "plugin" -d 'Generate shell plugin script'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from help" -f -a "theme" -d 'Generate shell theme'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from help" -f -a "doctor" -d 'Run diagnostics on shell environment'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from help" -f -a "rprompt" -d 'Get rprompt information (model and conversation stats) for shell integration'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from help" -f -a "setup" -d 'Setup zsh integration by updating .zshrc with plugin and theme'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from help" -f -a "keyboard" -d 'Show keyboard shortcuts for ZSH line editor'
complete -c forge -n "__fish_forge_using_subcommand zsh; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "plugin" -d 'Generate fish shell plugin script'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "theme" -d 'Generate fish shell theme'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "doctor" -d 'Run diagnostics on fish shell environment'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "rprompt" -d 'Get rprompt information (model and conversation stats) for fish shell integration'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "setup" -d 'Setup fish integration by updating config.fish with plugin and theme'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "keyboard" -d 'Show keyboard shortcuts for Fish shell'
complete -c forge -n "__fish_forge_using_subcommand fish; and not __fish_seen_subcommand_from plugin theme doctor rprompt setup keyboard help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from plugin" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from theme" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from doctor" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from rprompt" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from setup" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from keyboard" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from help" -f -a "plugin" -d 'Generate fish shell plugin script'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from help" -f -a "theme" -d 'Generate fish shell theme'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from help" -f -a "doctor" -d 'Run diagnostics on fish shell environment'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from help" -f -a "rprompt" -d 'Get rprompt information (model and conversation stats) for fish shell integration'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from help" -f -a "setup" -d 'Setup fish integration by updating config.fish with plugin and theme'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from help" -f -a "keyboard" -d 'Show keyboard shortcuts for Fish shell'
complete -c forge -n "__fish_forge_using_subcommand fish; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "agent" -d 'List available agents'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "provider" -d 'List available API providers'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "model" -d 'List available models'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "command" -d 'List available commands'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "config" -d 'List configuration values'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "tool" -d 'List tools for a specific agent'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "mcp" -d 'List MCP servers'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "conversation" -d 'List conversation history'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "cmd" -d 'List custom commands'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "skill" -d 'List available skills'
complete -c forge -n "__fish_forge_using_subcommand list; and not __fish_seen_subcommand_from agent provider model command config tool mcp conversation cmd skill help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from agent" -l custom -d 'Shows only custom agents'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from agent" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from agent" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from provider" -s t -l type -d 'Filter providers by type (e.g., llm, context_engine). Can be specified multiple times' -r
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from provider" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from provider" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from model" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from model" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from command" -l custom -d 'Shows only custom commands'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from command" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from command" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from config" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from config" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from tool" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from tool" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from mcp" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from mcp" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from conversation" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from conversation" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from cmd" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from cmd" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from skill" -l custom -d 'Shows only custom skills'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from skill" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from skill" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "agent" -d 'List available agents'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "provider" -d 'List available API providers'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "model" -d 'List available models'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "command" -d 'List available commands'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "config" -d 'List configuration values'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "tool" -d 'List tools for a specific agent'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "mcp" -d 'List MCP servers'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "conversation" -d 'List conversation history'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "cmd" -d 'List custom commands'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "skill" -d 'List available skills'
complete -c forge -n "__fish_forge_using_subcommand list; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand banner" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand info" -l conversation-id -d 'Conversation ID for session-specific information' -r
complete -c forge -n "__fish_forge_using_subcommand info" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand info" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand env" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand config; and not __fish_seen_subcommand_from set get list help" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand config; and not __fish_seen_subcommand_from set get list help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand config; and not __fish_seen_subcommand_from set get list help" -f -a "set" -d 'Set a configuration value'
complete -c forge -n "__fish_forge_using_subcommand config; and not __fish_seen_subcommand_from set get list help" -f -a "get" -d 'Get a configuration value'
complete -c forge -n "__fish_forge_using_subcommand config; and not __fish_seen_subcommand_from set get list help" -f -a "list" -d 'List configuration values'
complete -c forge -n "__fish_forge_using_subcommand config; and not __fish_seen_subcommand_from set get list help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -f -a "model" -d 'Set the active model'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -f -a "provider" -d 'Set the active provider'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -f -a "commit" -d 'Set the provider and model for commit message generation'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -f -a "suggest" -d 'Set the provider and model for command suggestion generation'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -f -a "reasoning-effort" -d 'Set the reasoning effort level applied to all agents'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from set" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -f -a "model" -d 'Get the active model'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -f -a "provider" -d 'Get the active provider'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -f -a "commit" -d 'Get the commit message generation config'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -f -a "suggest" -d 'Get the command suggestion generation config'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -f -a "reasoning-effort" -d 'Get the reasoning effort level'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from get" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from list" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set a configuration value'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "get" -d 'Get a configuration value'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "list" -d 'List configuration values'
complete -c forge -n "__fish_forge_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "list" -d 'List conversation history'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "new" -d 'Create a new conversation'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "dump" -d 'Export conversation as JSON or HTML'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "compact" -d 'Compact conversation to reduce token usage'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "retry" -d 'Retry last command without modifying context'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "resume" -d 'Resume conversation in interactive mode'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "show" -d 'Show last assistant message'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "info" -d 'Show conversation details'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "stats" -d 'Show conversation statistics'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "clone" -d 'Clone conversation with a new ID'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "delete" -d 'Delete a conversation permanently'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "rename" -d 'Rename a conversation'
complete -c forge -n "__fish_forge_using_subcommand conversation; and not __fish_seen_subcommand_from list new dump compact retry resume show info stats clone delete rename help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from list" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from dump" -l html -d 'Export as HTML instead of JSON'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from dump" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from compact" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from retry" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from resume" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from show" -l md -d 'Print raw markdown without rendering'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from stats" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from stats" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from clone" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from clone" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from rename" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "list" -d 'List conversation history'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "new" -d 'Create a new conversation'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "dump" -d 'Export conversation as JSON or HTML'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "compact" -d 'Compact conversation to reduce token usage'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "retry" -d 'Retry last command without modifying context'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "resume" -d 'Resume conversation in interactive mode'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show last assistant message'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "info" -d 'Show conversation details'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "stats" -d 'Show conversation statistics'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "clone" -d 'Clone conversation with a new ID'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete a conversation permanently'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "rename" -d 'Rename a conversation'
complete -c forge -n "__fish_forge_using_subcommand conversation; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand commit" -l max-diff -d 'Maximum git diff size in bytes (default: 100k)' -r
complete -c forge -n "__fish_forge_using_subcommand commit" -l preview -d 'Preview the commit message without committing'
complete -c forge -n "__fish_forge_using_subcommand commit" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -f -a "import" -d 'Import server configuration from JSON'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -f -a "list" -d 'List configured servers'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -f -a "remove" -d 'Remove a configured server'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -f -a "show" -d 'Show server configuration details'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -f -a "reload" -d 'Reload servers and rebuild caches'
complete -c forge -n "__fish_forge_using_subcommand mcp; and not __fish_seen_subcommand_from import list remove show reload help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from import" -s s -l scope -d 'Configuration scope' -r -f -a "local\t'Local configuration (project-specific)'
user\t'User configuration (global to the user)'"
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from import" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from import" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from list" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from remove" -s s -l scope -d 'Configuration scope' -r -f -a "local\t'Local configuration (project-specific)'
user\t'User configuration (global to the user)'"
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from remove" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from show" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from reload" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from reload" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from help" -f -a "import" -d 'Import server configuration from JSON'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from help" -f -a "list" -d 'List configured servers'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove a configured server'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show server configuration details'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from help" -f -a "reload" -d 'Reload servers and rebuild caches'
complete -c forge -n "__fish_forge_using_subcommand mcp; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand suggest" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand provider; and not __fish_seen_subcommand_from login logout list help" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand provider; and not __fish_seen_subcommand_from login logout list help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand provider; and not __fish_seen_subcommand_from login logout list help" -f -a "login" -d 'Authenticate with an API provider'
complete -c forge -n "__fish_forge_using_subcommand provider; and not __fish_seen_subcommand_from login logout list help" -f -a "logout" -d 'Remove provider credentials'
complete -c forge -n "__fish_forge_using_subcommand provider; and not __fish_seen_subcommand_from login logout list help" -f -a "list" -d 'List available providers'
complete -c forge -n "__fish_forge_using_subcommand provider; and not __fish_seen_subcommand_from login logout list help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from login" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from login" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from logout" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from logout" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from list" -s t -l type -d 'Filter providers by type (e.g., llm, context_engine). Can be specified multiple times' -r
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from list" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from help" -f -a "login" -d 'Authenticate with an API provider'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from help" -f -a "logout" -d 'Remove provider credentials'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from help" -f -a "list" -d 'List available providers'
complete -c forge -n "__fish_forge_using_subcommand provider; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand cmd; and not __fish_seen_subcommand_from list execute help" -l conversation-id -d 'Conversation ID to execute the command within' -r
complete -c forge -n "__fish_forge_using_subcommand cmd; and not __fish_seen_subcommand_from list execute help" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand cmd; and not __fish_seen_subcommand_from list execute help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand cmd; and not __fish_seen_subcommand_from list execute help" -f -a "list" -d 'List all available custom commands'
complete -c forge -n "__fish_forge_using_subcommand cmd; and not __fish_seen_subcommand_from list execute help" -f -a "execute" -d 'Execute a custom command'
complete -c forge -n "__fish_forge_using_subcommand cmd; and not __fish_seen_subcommand_from list execute help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from list" -l conversation-id -d 'Conversation ID to execute the command within' -r
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from list" -l custom -d 'Shows only custom commands'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from list" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from execute" -l conversation-id -d 'Conversation ID to execute the command within' -r
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from execute" -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from execute" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all available custom commands'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from help" -f -a "execute" -d 'Execute a custom command'
complete -c forge -n "__fish_forge_using_subcommand cmd; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "sync" -d 'Synchronize a directory for semantic search'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "list" -d 'List all workspaces'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "query" -d 'Query the workspace'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "info" -d 'Show workspace information for an indexed directory'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "delete" -d 'Delete one or more workspaces'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "status" -d 'Show sync status of all files in the workspace'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "init" -d 'Initialize an empty workspace for the provided directory'
complete -c forge -n "__fish_forge_using_subcommand workspace; and not __fish_seen_subcommand_from sync list query info delete status init help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from sync" -l init -d 'Automatically initialize the workspace before syncing if it has not been initialized yet'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from list" -s p -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from query" -s l -l limit -d 'Maximum number of results to return' -r
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from query" -l top-k -d 'Number of highest probability tokens to consider (1-1000)' -r
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from query" -s r -l use-case -d 'Describe your intent or goal to filter results for relevance' -r
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from query" -l starts-with -d 'Filter results to files starting with this prefix' -r
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from query" -l ends-with -d 'Filter results to files ending with this suffix' -r
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from query" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from status" -s p -l porcelain -d 'Output in machine-readable format'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Synchronize a directory for semantic search'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all workspaces'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "query" -d 'Query the workspace'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "info" -d 'Show workspace information for an indexed directory'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete one or more workspaces'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show sync status of all files in the workspace'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize an empty workspace for the provided directory'
complete -c forge -n "__fish_forge_using_subcommand workspace; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand data" -l input -d 'Path to JSONL file to process' -r
complete -c forge -n "__fish_forge_using_subcommand data" -l schema -d 'Path to JSON schema file for LLM tool definition' -r
complete -c forge -n "__fish_forge_using_subcommand data" -l system-prompt -d 'Path to Handlebars template file for system prompt' -r
complete -c forge -n "__fish_forge_using_subcommand data" -l user-prompt -d 'Path to Handlebars template file for user prompt' -r
complete -c forge -n "__fish_forge_using_subcommand data" -l concurrency -d 'Maximum number of concurrent LLM requests' -r
complete -c forge -n "__fish_forge_using_subcommand data" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand vscode; and not __fish_seen_subcommand_from install-extension help" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand vscode; and not __fish_seen_subcommand_from install-extension help" -f -a "install-extension" -d 'Install the Forge VS Code extension'
complete -c forge -n "__fish_forge_using_subcommand vscode; and not __fish_seen_subcommand_from install-extension help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand vscode; and __fish_seen_subcommand_from install-extension" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand vscode; and __fish_seen_subcommand_from help" -f -a "install-extension" -d 'Install the Forge VS Code extension'
complete -c forge -n "__fish_forge_using_subcommand vscode; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand update" -l no-confirm -d 'Skip the confirmation prompt when applying updates'
complete -c forge -n "__fish_forge_using_subcommand update" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand setup" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand doctor" -s h -l help -d 'Print help'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "agent" -d 'Manage agents'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "zsh" -d 'Generate shell extension scripts'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "fish" -d 'Generate fish shell extension scripts'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "list" -d 'List agents, models, providers, tools, or MCP servers'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "banner" -d 'Display the banner with version information'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "info" -d 'Show configuration, active model, and environment status'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "env" -d 'Display environment information'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "config" -d 'Get, set, or list configuration values'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "conversation" -d 'Manage conversation history and state'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "commit" -d 'Generate and optionally commit changes with AI-generated message'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "mcp" -d 'Manage Model Context Protocol servers'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "suggest" -d 'Suggest shell commands from natural language'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "provider" -d 'Manage API provider authentication'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "cmd" -d 'Run or list custom commands'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "workspace" -d 'Manage workspaces for semantic search'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "data" -d 'Process JSONL data through LLM with schema-constrained tools'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "vscode" -d 'VS Code integration commands'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "update" -d 'Update forge to the latest version'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "setup" -d 'Setup zsh integration by updating .zshrc with plugin and theme (alias for `zsh setup`)'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "doctor" -d 'Run diagnostics on shell environment (alias for `zsh doctor`)'
complete -c forge -n "__fish_forge_using_subcommand help; and not __fish_seen_subcommand_from agent zsh fish list banner info env config conversation commit mcp suggest provider cmd workspace data vscode update setup doctor help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from agent" -f -a "list" -d 'List available agents'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from zsh" -f -a "plugin" -d 'Generate shell plugin script'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from zsh" -f -a "theme" -d 'Generate shell theme'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from zsh" -f -a "doctor" -d 'Run diagnostics on shell environment'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from zsh" -f -a "rprompt" -d 'Get rprompt information (model and conversation stats) for shell integration'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from zsh" -f -a "setup" -d 'Setup zsh integration by updating .zshrc with plugin and theme'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from zsh" -f -a "keyboard" -d 'Show keyboard shortcuts for ZSH line editor'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from fish" -f -a "plugin" -d 'Generate fish shell plugin script'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from fish" -f -a "theme" -d 'Generate fish shell theme'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from fish" -f -a "doctor" -d 'Run diagnostics on fish shell environment'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from fish" -f -a "rprompt" -d 'Get rprompt information (model and conversation stats) for fish shell integration'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from fish" -f -a "setup" -d 'Setup fish integration by updating config.fish with plugin and theme'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from fish" -f -a "keyboard" -d 'Show keyboard shortcuts for Fish shell'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "agent" -d 'List available agents'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "provider" -d 'List available API providers'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "model" -d 'List available models'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "command" -d 'List available commands'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "config" -d 'List configuration values'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "tool" -d 'List tools for a specific agent'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "mcp" -d 'List MCP servers'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "conversation" -d 'List conversation history'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "cmd" -d 'List custom commands'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from list" -f -a "skill" -d 'List available skills'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "set" -d 'Set a configuration value'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "get" -d 'Get a configuration value'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "list" -d 'List configuration values'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "list" -d 'List conversation history'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "new" -d 'Create a new conversation'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "dump" -d 'Export conversation as JSON or HTML'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "compact" -d 'Compact conversation to reduce token usage'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "retry" -d 'Retry last command without modifying context'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "resume" -d 'Resume conversation in interactive mode'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "show" -d 'Show last assistant message'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "info" -d 'Show conversation details'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "stats" -d 'Show conversation statistics'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "clone" -d 'Clone conversation with a new ID'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "delete" -d 'Delete a conversation permanently'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from conversation" -f -a "rename" -d 'Rename a conversation'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from mcp" -f -a "import" -d 'Import server configuration from JSON'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from mcp" -f -a "list" -d 'List configured servers'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from mcp" -f -a "remove" -d 'Remove a configured server'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from mcp" -f -a "show" -d 'Show server configuration details'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from mcp" -f -a "reload" -d 'Reload servers and rebuild caches'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from provider" -f -a "login" -d 'Authenticate with an API provider'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from provider" -f -a "logout" -d 'Remove provider credentials'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from provider" -f -a "list" -d 'List available providers'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from cmd" -f -a "list" -d 'List all available custom commands'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from cmd" -f -a "execute" -d 'Execute a custom command'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from workspace" -f -a "sync" -d 'Synchronize a directory for semantic search'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from workspace" -f -a "list" -d 'List all workspaces'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from workspace" -f -a "query" -d 'Query the workspace'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from workspace" -f -a "info" -d 'Show workspace information for an indexed directory'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from workspace" -f -a "delete" -d 'Delete one or more workspaces'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from workspace" -f -a "status" -d 'Show sync status of all files in the workspace'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from workspace" -f -a "init" -d 'Initialize an empty workspace for the provided directory'
complete -c forge -n "__fish_forge_using_subcommand help; and __fish_seen_subcommand_from vscode" -f -a "install-extension" -d 'Install the Forge VS Code extension'
